osx_image: xcode8
language: objective-c
before_install:
- gem install cocoapods --pre --no-document
script:
- open -b com.apple.iphonesimulator
- xcodebuild -scheme UILocalNotification-RemotePayload -project UILocalNotification-RemotePayload.xcodeproj -sdk iphonesimulator10.0 -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' build test | xcpretty
- pod lib lint
after_success:
- bash <(curl -s https://codecov.io/bash)
